### ISSUE TITLE
Question about problem1

### ISSUE THREAD

**Issue by NatthananRuengchaijatuporn** [sirasris/AI_Academy_2020#3]
Is it valid for exposure time to be negative value? Or Is it designed to be wrong data that examinees need to handle?

**Comment by sirasris** [comment]
> Is it valid for exposure time to be negative value? Or Is it designed to be wrong data that examinees need to handle?

Good catch! But don't worry, this is not a trap! 

Negative values in **Exposure_Time** is used to indicate that the patient takes the drug **AFTER** the testing. This happened for example when a patient has to take drugs A and B. When this patient showed allergic reaction after taking drug A, ELISpot tests were performed for both drugs A and B. So the **Exposure_Time** for drug B in this case will be negative. 

For the purpose of this exam, we will not penalize the examinee for not noticing this issue.
