### ISSUE TITLE
Would like to know whether Thai language can be used to describe work procedures

### ISSUE THREAD

**Issue by Mickey248** [sirasris/AI_Academy_2020#4]
Some things are quite difficult to explain if in English, so I would like to explain in Thai for better understanding.
Yes or no?

**Comment by sirasris** [comment]
ถ้าไม่มั่นใจ สามารถส่งคำตอบเป็นภาษาไทยได้ครับ เน้นให้สื่อสารรายละเอียดได้ถูกต้องครับ
